import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { House, BarChart2, Settings } from "lucide-react";
import Link from "next/link";
import { AuthChecker } from "@/libraries/authCheck";
// import Image from "next/image";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const menuItems = [
  { name: "Dashboard", icon: House, href: "/dashboard" },
  { name: "Inventory Accounting", icon: BarChart2, href: "/dashboard/cashflow-statements/inventory-accounting" },
  { name: "Operator Accounting", icon: Settings, href: "/dashboard/cashflow-statements/operator-accounting" },
  { name: "Operational Accounting", icon: Settings, href: "/dashboard/cashflow-statements/operational-accounting" },
  { name: "Veggies Order", icon: Settings, href: "/dashboard/cashflow-statements/veggies-order" },
];

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {

  return (
    <html lang="en">
      <AuthChecker/>
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased flex`}>
        <aside className="bg-gray-900 text-white w-64 min-h-screen p-4">
          <h2 className="text-2xl font-bold mb-6">My Dashboard</h2>
          <nav className="space-y-2">
            {menuItems.map((item) => (
              <Link
                key={item.name}
                href={item.href}
                className="flex items-center gap-2 p-2 rounded hover:bg-gray-700 transition"
              >
                <item.icon size={20} />
                {item.name}
              </Link>
            ))}
          </nav>
        </aside>
        <div className="flex-1 flex flex-col">
          <header className="bg-white shadow p-4 flex justify-between items-center">
            <h1 className="text-xl font-semibold">Dashboard</h1>
            <div className="flex items-center gap-4">
              <span className="text-gray-600">Hello, User</span>
              {/* <Image
              src="https://ui-avatars.com/api/?name=User&background=random"
              alt="avatar"
              className="w-10 h-10 rounded-full"
              width={100}
              height={100}
            /> */}
            </div>
          </header>
          <main className="p-6 min-h-screen">{children}</main>
        </div>
      </body>
    </html>
  );
}
